- Desk, computer, materials already set up.
- Added to appropriate groups and standing meetings
- Block off on boarding meetings, computer set up time
- Wifi, Space Tour
- 1 hour Time set aside for digital set up
- New Employee Email sent
